C
C     SUBROUTINE INICON      
C
C*** *INICON*  PRESET CONSTANTS IN *COMCON*, *FAKTINF*
C
C             R. PODZUN    DKRZ     19/01/1995.
C
C     PURPOSE.
C     --------
C
C             PRESET CONSTANTS IN *COMCON*, *COMCUMF*.
C
C**   INTERFACE.
C     ----------
C
C             *INICON* IS CALLED FROM *INIT*.
C
C     EXTERNALS.
C     ----------
C
C             NONE.
C
      SUBROUTINE INICON(PR,PRD,PWCP,PWLK,PWLF,PWLS,PG,PRERD,
     &                  PRHF,PSIGMA,PSOKO)
C
      USE MO_COMDIA
      USE MO_COMCON
      USE MO_COMCUMF
      USE MO_HIGKON
      USE MO_PARKON
C
      IMPLICIT NONE
C
      REAL, INTENT(IN) :: PR,PRD,PWCP,PWLK,PWLF,PWLS,PG,PRERD,
     &                    PRHF,PSIGMA,PSOKO
C
      LMFPEN=.TRUE.
      LMFSCV=.TRUE.
      LMFMID=.TRUE.
      LMFDD=.TRUE.
      LMFDUDV=.TRUE.
C
      API=PI
      A=PRERD
      OMEGA=.7292E-4
      G=PG
      CPD=PWCP
      CPV=1869.46
      RD=PR
      RV=PRD
      RCPD=WCPR
      VTMPC1=RDDRM1
      VTMPC2=CPV/CPD-1.
      RHOH2O=PRHF
      ALV=PWLK
      ALS=PWLS
      ALF=PWLF
      CLW=4186.84
      TMELT=B3
      SOLC=PSOKO
      STBO=PSIGMA
      DAYL=86400.
      IF (LMOMON) THEN
         YEARL=360.
      ELSE
         IF (LLEAP) THEN
           YEARL=365.2425
         ELSE
           YEARL=365.
         ENDIF
      ENDIF
      C1ES=B1
      C2ES=B1*RDRD
      C3LES=B2W
      C3IES=B2E
      C4LES=B4W
      C4IES=B4E
      C5LES=B234W
      C5IES=B2E*(B3-B4E)
C     ENTRPEN: AVERAGE ENTRAINMENT RATE FOR PENETRATIVE CONVECTION
      ENTRPEN=1.0E-4
C     ENTRSCV: AVERAGE ENTRAINMENT RATE FOR SHALLOW CONVECTION
      ENTRSCV=3.0E-4
C     ENTRMID: AVERAGE ENTRAINMENT RATE FOR MIDLEVEL CONVECTION
      ENTRMID=1.0E-4
C     ENTRDD: AVERAGE ENTRAINMENT RATE FOR DOWNDRAFTS
      ENTRDD =2.0E-4
C     CMFCTOP:   RELATIVE CLOUD MASSFLUX AT LEVEL ABOVE NONBUOYANCY LEVE
      CMFCTOP=0.1
C     CMFCMAX:   MAXIMUM MASSFLUX VALUE ALLOWED FOR UPDRAFTS ETC
      CMFCMAX=1.0
C     CMFCMIN:   MINIMUM MASSFLUX VALUE (FOR SAFETY)
      CMFCMIN=1.E-10
C     CMFDEPS:   FRACTIONAL MASSFLUX FOR DOWNDRAFTS AT LFS
      CMFDEPS=0.3
C     CPRCON:    COEFFICIENTS FOR DETERMINING CONVERSION FROM CLOUD WATE
      CPRCON=1.E-2
C     NEXT VALUE IS RELATIVE SATURATION IN DOWNDRAFRS
C     BUT IS NO LONGER USED ( FORMULATION IMPLIES SATURATION)
      RHCDD=1.
C
      TCRITH=273.16
      TCRITL=268.16
C
CKS   CONSTANTS USED IN VDIFF AND EXCHGCOEFF
C
      ZCONS16=CPD*VTMPC2
      RVRD=VTMPC1+1.
      RDRV=1./RVRD
      KAPPA=RD/CPD
C
C     CONSTANT FOR FREE CONVECTION
C     EXPONENT FOR THE INTERPOLATION BETWEEN FREE CONVECTION
C     AND NEUTRAL OVER SEA
C
C     FREECON=0.002
      FREECON=0.0016
      GAM=1.25
      RGAM=1./GAM
C
C*    PARAMETERS FOR BOUNDARY LAYER DIAGNOSTICS
C     ---------- --- -------- ----- -----------
C
      HUV=10.*G
      HTQ=2.*G
      RHOS=RHOH2O*1.025
CKS
      RETURN
      END SUBROUTINE INICON
