C
      MODULE MO_COMDYN
C
      IMPLICIT NONE
C
      LOGICAL ::          LSITS, LVNEST, L2DREMO, LHDIFF2, LDIVDAMP,
     &                    LRAYDAMP
C
      REAL    ::          VBMXV , EPSASS, VBCFL, DT, ALCNVA, SITR,
     &                    SIPSR , CODAMP
C

C**** COMDYN   -   CB:STEUERPARAMETER DER ADIABATISCHEN PROGNOSE
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   LSITS    :   TRUE:  SI-ZEITINTEGRATION;                 (--)
C**                FALSE: EXPLIZITER ZEITSCHRITT
C**   EPSASS   :   EPS IM ASSELIN-FILTER                      (--)
C**   DT       :   ZEITSCHRITT                                (S)
C**   ALCNVA   :   STEUERUNG DES IMPLIZITHEITSGRADES DER      (--)
C**                VERTIKALADVEKTION
C**   SITR     :   REFERENZTEMPERATUR FUER SI-SCHEMA          (K)
C**   SIPSR    :   REFERENZBODENDRUCK FUER SI-SCHEMA          (PA)
C**   LVNEST   :   TRUE:  VERTIKALES NESTING AN RAHMENMODELL  (--)
C**                FALSE: KEIN VERTIKALES NESTING AN RAHMENMODELL
C**   VBMXV    :   MAXIMALE WINDGESCHWINDIGKEIT IM GESAMTEN   (M/S)
C**                VORHERSAGEVOLUMEN
C**   VBCFL    :   MAXIMALE WINDGESCHWINDIGKEIT (CFL-KRITER.) (M/S)
C**
C**   VERFASSER:   D.MAJEWSKI
C     17.11.15: CONVERTED TO MODULE (LARS BUNTEMEYER)
C
      END MODULE MO_COMDYN
