#!/bin/csh -f

#try running the python interpreter the way setup.py does, check exit code.
/usr/bin/env python -c " " >& /dev/null

if ($status) then
  echo "Error: Python interpreter not found"
  exit 1
else
  cd bin
  ./setup.py $argv
  exit $status
endif
  





