#
# makefile for driver module
#

Driver += Driver.o Driver_data.o Driver_init_nerd.o Driver_finish_nerd.o \
          Driver_evolve_nerd.o 

Driver.o : Driver_data.o

Driver_init_nerd.o : RuntimeParameters.o Grid.o Database.o Hydro.o

