! Runtime-settable parameter initializations;
! generated by setup script.
! Do not edit!

subroutine init_global_parms(parmfile)

use runtime_parameters

character(len=*) :: parmfile

call create_parm_context (global_parm_context)
call create_global_parms
call read_parameters (parmfile, global_parm_context)
call get_global_parms
return
end


subroutine create_global_parms

use runtime_parameters
implicit none


return 
end



subroutine get_global_parms

use runtime_parameters
use global_runtime_dec


return
end
