#!/bin/sh -f

#		Script to create a subroutine which writes a 'build stamp'
#		to the log file

rm -f buildstamp.f
echo '      ' subroutine build_stamp \(s_stamp_str, b_stamp_str, str_len\) >> buildstamp.f
echo '      ' implicit none >> buildstamp.f
echo '      ' integer                  :: str_len >> buildstamp.f
echo '      ' character\(len=str_len\) :: s_stamp_str, b_stamp_str >> buildstamp.f
echo '      ' s_stamp_str = \'Sat Aug 17 17:44:46 2013\'  >> buildstamp.f
echo '      ' b_stamp_str = \'`date`\'  >> buildstamp.f
echo '      ' return >> buildstamp.f
echo '      ' end subroutine >> buildstamp.f
echo '      ' >> buildstamp.f
echo '      ' subroutine system_info \(system_str, str_len\) >> buildstamp.f
echo '      ' integer                  :: str_len >> buildstamp.f
echo '      ' character\(len=str_len\) :: system_str >> buildstamp.f
echo '      ' system_str = >> buildstamp.f
echo '     &' \'Linux hspc48 3.2.0-51-generic x86_64\'  >> buildstamp.f
echo '      ' return >> buildstamp.f
echo '      ' end subroutine >> buildstamp.f
echo '      ' >> buildstamp.f

