database = mo_database.o init_database.o mo_constants.o mo_parameters.o \
           dBaseDeclarations.o dump_parameters.o

dump_parameters.o: mo_parameters.o

dBaseDeclarations.o: mo_parameters.o

mo_database.o: mo_grid.o

init_database.o: mo_database.o
