MODULE MO_MAGNUS

USE mo_constants, ONLY:   RDRD, EMRDRD, B1, B3, B4W, B2W, B2E, B4E

IMPLICIT NONE


CONTAINS

! STATEMENT - FUNCTIONS ZUR BERECHNUNG DER SAEETIGUNGSFEUCHTE
! MAGNUS-FORMEL FUER WASSER

REAL FUNCTION FGEW(TT)
   IMPLICIT NONE
   REAL, INTENT(IN) :: TT
   FGEW = B1 * EXP( B2W*(TT - B3)/(TT - B4W) )
END FUNCTION FGEW
!  
REAL FUNCTION FGEE(TT)
   IMPLICIT NONE
   REAL, INTENT(IN) :: TT
   FGEE = B1 * EXP  ( B2E*(TT - B3)/(TT - B4E) )
END FUNCTION FGEE
!
! SPEZIFISCHE FEUCHTE AUS DAMPFDRUCK UND LUFTDRUCK
!
REAL FUNCTION FGQD(GE,PP)
   IMPLICIT NONE
   REAL, INTENT(IN) :: GE,PP
   FGQD = RDRD*GE/(PP - EMRDRD*GE)
END FUNCTION FGQD


END MODULE MO_MAGNUS
