#
# makefile for driver module
#

Simulation += Simulation.o Simulation_data.o Simulation_init_domain.o 

Simulation.o : Simulation_data.o

Simulation_init_domain.o : Simulation_data.o Grid.o Database.o RuntimeParameters.o 

