#
# makefile for hydro module
#

Hydro += Hydro.o Hydro_init.o Hydro_data.o Hydro_solve.o Hydro_cfl_timestep.o

Hydro.o : Hydro_data.o Hydro_solve.o

Hydro_solve.o : Grid.o Database.o RuntimeParameters.o
