#
# makefile for database module
#

RuntimeParameters += RuntimeParameters.o RuntimeParameters_data.o \
                     RuntimeParameters_init.o

RuntimeParameters.o : RuntimeParameters_data.o

RuntimeParameters_init.o : RuntimeParameters_data.o
